# Generated by Django 5.2.7 on 2025-11-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
