# Generated by Django 5.2.7 on 2025-11-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cliente_codigo_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='leido',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Contacto'), ('ESPERA', 'Esperando Respuesta del Cliente'), ('LISTO', 'Gestionado / Resuelto'), ('CANCELADO', 'Pedido Anulado')], default='PENDIENTE', max_length=20),
        ),
    ]
