# Generated by Django 5.2.7 on 2025-11-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_notificacion_leido_notificacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
