# Generated by Django 5.2.7 on 2025-12-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_pedido_codigo_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('Despacho', 'Despacho a Domicilio'), ('Retiro', 'Retiro en Tienda')], default='Despacho', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Preparacion', 'En Preparación'), ('En Espera Faltante', 'En espera por faltante'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
    ]
