# Generated by Django 5.2.7 on 2025-12-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_pedido_tipo_entrega_alter_pedido_codigo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
    ]
