# Generated by Django 5.2.7 on 2025-12-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Preparacion', 'En Preparación'), ('En Espera Faltante', 'En espera por faltante'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Reserva Pendiente', 'Reserva Solicitada a Soporte'), ('Reserva En Camino', 'Producto Solicitado al Proveedor'), ('Reserva Disponible', 'Disponible para Pago')], default='Pendiente', max_length=50),
        ),
    ]
